const STORAGE_KEY="rtm_v01_records";let records=loadRecords(),activeFilter="all";const $=id=>document.getElementById(id);
function loadRecords(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(Array.isArray(saved)&&saved.length)return saved}catch(e){}return JSON.parse(JSON.stringify(window.RECIPES||[]))}
function saveRecords(){localStorage.setItem(STORAGE_KEY,JSON.stringify(records))}
function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function show(view){["catalogView","detailView","formView"].forEach(id=>$(id).classList.toggle("hidden",id!==view));window.scrollTo({top:0,behavior:"smooth"})}
function matches(r,q){return [r.title,r.origin,r.author,r.type,r.family,r.status,...(r.ingredients||[]),...(r.tags||[])].join(" ").toLowerCase().includes(q)}
function renderCatalog(){const q=$("searchInput").value.trim().toLowerCase();const filtered=records.filter(r=>activeFilter==="all"||r.record_type===activeFilter).filter(r=>!q||matches(r,q)).sort((a,b)=>a.title.localeCompare(b.title,"es"));$("count").textContent=`${filtered.length} ${filtered.length===1?"ficha":"fichas"}`;$("catalog").innerHTML=filtered.map(r=>`<article class="card ${r.record_type==="technique"?"technique":""}" data-id="${esc(r.id)}"><div class="card-bar"></div><div class="card-image">${esc(r.emoji||(r.record_type==="technique"?"🥣":"🍽️"))}</div><div class="card-body"><span class="kind">${r.record_type==="technique"?"Técnica culinaria":"Receta"}</span><h2>${esc(r.title)}</h2><p>${esc(r.family||r.origin||"")}</p></div></article>`).join("")||`<p class="count">No se han encontrado fichas.</p>`;document.querySelectorAll(".card").forEach(c=>c.addEventListener("click",()=>openRecord(c.dataset.id)))}
function quick(l,v){return `<div><b>${l}</b>${esc(v||"No indicado")}</div>`}
function openRecord(id){const r=records.find(x=>x.id===id);if(!r)return;$("detail").innerHTML=`<header class="detail-head ${r.record_type==="technique"?"technique":""}"><span class="kind">${r.record_type==="technique"?"Técnica culinaria":"Receta"}</span><h1>${esc(r.title)}</h1><p class="detail-sub">${esc([r.author,r.origin].filter(Boolean).join(" · "))}</p></header><div class="detail-body"><div class="quick">${quick("Tipo",r.type)}${quick("Familia culinaria",r.family)}${quick("Raciones",r.servings)}${quick("Tiempo",r.time)}${quick("Dificultad",r.difficulty)}</div><h2>Ingredientes</h2><ul>${(r.ingredients||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul><h2>Preparación</h2><ol>${(r.steps||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ol>${r.presentation?`<h2>Presentación</h2><p>${esc(r.presentation)}</p>`:""}${r.tips?`<h2>Consejos</h2><div class="note">${esc(r.tips)}</div>`:""}${r.status||r.notes?`<h2>Mi valoración</h2><p><b>Estado:</b> ${esc(r.status||"—")}</p>${r.notes?`<p>${esc(r.notes)}</p>`:""}`:""}<div class="tags">${(r.tags||[]).map(t=>`<span class="tag">#${esc(t.replace(/^#/,""))}</span>`).join("")}</div><div class="detail-actions"><button class="primary" onclick="editRecord('${esc(r.id)}')">Editar</button><button onclick="window.print()">Guardar PDF</button><button onclick="deleteRecord('${esc(r.id)}')">Eliminar</button></div></div>`;show("detailView")}
function emptyForm(){const f=$("recipeForm");f.reset();f.elements.id.value="";$("formTitle").textContent="Añadir ficha"}
function editRecord(id){const r=records.find(x=>x.id===id);if(!r)return;const f=$("recipeForm");const values={id:r.id,record_type:r.record_type,title:r.title,origin:r.origin,author:r.author,type:r.type,family:r.family,servings:r.servings,time:r.time,difficulty:r.difficulty,status:r.status,ingredients:(r.ingredients||[]).join("\n"),steps:(r.steps||[]).join("\n"),presentation:r.presentation,tips:r.tips,notes:r.notes,tags:(r.tags||[]).join(", ")};Object.entries(values).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v||""});$("formTitle").textContent="Editar ficha";show("formView")}
function deleteRecord(id){if(!confirm("¿Eliminar esta ficha?"))return;records=records.filter(r=>r.id!==id);saveRecords();renderCatalog();show("catalogView")}
$("recipeForm").addEventListener("submit",e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target).entries());const data={record_type:o.record_type,title:o.title.trim(),origin:o.origin.trim(),author:o.author.trim(),type:o.type.trim(),family:o.family.trim(),servings:o.servings.trim(),time:o.time.trim(),difficulty:o.difficulty.trim(),status:o.status.trim(),ingredients:o.ingredients.split(/\n+/).map(x=>x.trim()).filter(Boolean),steps:o.steps.split(/\n+/).map(x=>x.replace(/^\d+[\.\-\)]\s*/,"").trim()).filter(Boolean),presentation:o.presentation.trim(),tips:o.tips.trim(),notes:o.notes.trim(),tags:o.tags.split(",").map(x=>x.trim().replace(/^#/,"")).filter(Boolean),emoji:o.record_type==="technique"?"🥣":"🍽️"};if(o.id){const i=records.findIndex(r=>r.id===o.id);records[i]={...records[i],...data}}else{data.id=`rtm-${Date.now()}`;records.push(data)}saveRecords();renderCatalog();show("catalogView")});
$("searchInput").addEventListener("input",renderCatalog);document.querySelector(".chips").addEventListener("click",e=>{if(!e.target.matches(".chip"))return;activeFilter=e.target.dataset.filter;document.querySelectorAll(".chip").forEach(c=>c.classList.toggle("active",c===e.target));renderCatalog()});$("addBtn").addEventListener("click",()=>{emptyForm();show("formView")});$("backBtn").addEventListener("click",()=>show("catalogView"));$("cancelBtn").addEventListener("click",()=>show("catalogView"));$("exportBtn").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(records,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="recetario_toni_merino.json";a.click();URL.revokeObjectURL(a.href)});$("importInput").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data))throw new Error();records=data;saveRecords();renderCatalog();show("catalogView")}catch(err){alert("El archivo no es una copia válida.")}});renderCatalog();
