window.RECIPES = [
  {
    "id": "rtm-0001",
    "record_type": "recipe",
    "title": "Escudella i carn d'olla – Iaia Pilar",
    "origin": "Receta familiar · Transcripción de manuscrito",
    "author": "Iaia Pilar",
    "type": "Plato tradicional",
    "family": "Sopas y cremas",
    "servings": "6-8 personas",
    "time": "1 h 15 min aprox. + cocción final",
    "difficulty": "Media",
    "ingredients": [
      "Huesos de ternera, de pollo y de caña.",
      "1 trozo de ternera.",
      "1 cuarto de pollo.",
      "1 cuarto de gallina.",
      "1/4 de pie de cerdo.",
      "1 trocito de rabo de cerdo.",
      "1 trocito de tocino.",
      "1 butifarra cruda.",
      "1 trocito de chorizo.",
      "Zanahoria.",
      "Apio, un poco.",
      "Puerro.",
      "Col, un poco.",
      "Patatas.",
      "Garbanzos, previamente hervidos.",
      "Carne picada de cerdo.",
      "1 huevo batido.",
      "Pan rallado, solo si la mezcla queda muy líquida.",
      "Harina, para enharinar."
    ],
    "steps": [
      "Pon los huesos de ternera, pollo y caña en una olla grande con agua fría.",
      "Cuando el agua empiece a hervir, añade la ternera, el pollo, la gallina, el pie de cerdo, el tocino y el rabo de cerdo.",
      "Deja cocer durante unos 45 min.",
      "Añade la zanahoria, el apio, el puerro y la col. Reserva las patatas para más adelante.",
      "Pasados unos 30 min, incorpora la pelota, la butifarra, el trocito de chorizo y las patatas.",
      "Mantén la cocción a fuego bajo-medio hasta que las carnes, la pelota y las patatas estén hechas.",
      "Al final, añade los garbanzos ya hervidos y deja que se calienten con el conjunto."
    ],
    "presentation": "Sirve el caldo y, por separado o en una fuente, las carnes, la pelota, las verduras, las patatas y los garbanzos.",
    "tips": "Mantén un hervor suave para que el caldo quede limpio. Incorpora los garbanzos al final porque ya están cocidos.",
    "status": "Pendiente de hacer",
    "rating": "",
    "notes": "",
    "tags": [
      "RecetaFamiliar",
      "PlatoTradicional",
      "Escudella",
      "CarnDOlla",
      "CocinaCatalana",
      "OllaTradicional",
      "Invierno"
    ],
    "emoji": "🍲"
  },
  {
    "id": "rtm-0002",
    "record_type": "recipe",
    "title": "Bisqué de langostinos (Thermomix)",
    "origin": "Transcripción de texto",
    "author": "",
    "type": "Primer plato",
    "family": "Sopas y cremas",
    "servings": "6 personas",
    "time": "1 h",
    "difficulty": "Fácil",
    "ingredients": [
      "500 g de langostinos.",
      "1 cubilete de aceite de oliva virgen extra.",
      "1 zanahoria.",
      "1 cebolla.",
      "1 puerro pequeño, solo la parte blanca.",
      "1 diente de ajo.",
      "1 hoja de laurel.",
      "100 g de tomate.",
      "250 g de patatas cocidas, sin que queden demasiado hechas.",
      "1 cubilete de vino blanco seco.",
      "1/2 cubilete de brandy.",
      "1 l de caldo de pescado.",
      "50 g de mantequilla.",
      "150 g de nata líquida.",
      "Perejil o cebollino.",
      "Sal y pimienta."
    ],
    "steps": [
      "Pela las patatas, córtalas en dados y cuécelas durante unos 15 min, hasta que estén cocidas pero firmes. Reserva.",
      "Pela los langostinos. Reserva las colas y las cabezas por separado.",
      "Pon en el vaso la zanahoria, la cebolla, el puerro y el ajo. Pica 10 s · velocidad 4.",
      "Baja los restos, añade el aceite y rehoga 10 min · 90 °C · velocidad 1.",
      "Incorpora las cabezas de los langostinos y el tomate. Rehoga 4 min · Varoma · velocidad 2.",
      "Añade el brandy y programa 3 min · Varoma · velocidad 2.",
      "Agrega el caldo, el vino, 150 g de patatas y el laurel. Cocina 40 min · 100 °C · velocidad 1.",
      "Deja bajar un poco la temperatura. Retira el laurel y las cabezas.",
      "Tritura a velocidad progresiva 6-8-10 hasta obtener una crema fina.",
      "Programa unos 3 min · Varoma · velocidad 1, hasta que comience a hervir.",
      "Añade la nata, la mantequilla, las colas y el resto de las patatas. Salpimenta y mezcla 2 min · 90 °C · velocidad cuchara.",
      "Deja reposar unos minutos antes de servir."
    ],
    "presentation": "Sirve el bisqué bien caliente, terminado con perejil o cebollino picado.",
    "tips": "No cuezas en exceso las patatas: una parte se tritura para dar cuerpo y el resto se incorpora en trozos al final.",
    "status": "Excelente",
    "rating": "",
    "notes": "Receta que Toni prepara desde hace años y que no falla en Navidad.",
    "tags": [
      "Thermomix",
      "Navidad",
      "Langostinos",
      "SopasYCremas",
      "Excelente"
    ],
    "emoji": "🍤"
  },
  {
    "id": "rtm-0003",
    "record_type": "technique",
    "title": "Caldo base para arroces",
    "origin": "Ficha pendiente de completar",
    "author": "",
    "type": "Base culinaria",
    "family": "Técnicas y bases",
    "servings": "No indicado",
    "time": "No indicado",
    "difficulty": "No indicada",
    "ingredients": [
      "Contenido pendiente de incorporar desde la ficha normalizada."
    ],
    "steps": [
      "Contenido pendiente de incorporar desde la ficha normalizada."
    ],
    "presentation": "",
    "tips": "",
    "status": "Pendiente de completar",
    "rating": "",
    "notes": "",
    "tags": [
      "TecnicaCulinaria",
      "Arroces",
      "CaldoBase"
    ],
    "emoji": "🥣"
  }
];
