// Recetario Toni Merino · Versión 1.3.0 · 30 fichas verificadas
window.RTM_DATA_VERSION = "1.3.0";
window.RECIPES = [
  {
    "id": "rtm-0001",
    "record_type": "recipe",
    "title": "Escudella i carn d'olla – Iaia Pilar",
    "origin": "Receta familiar · Transcripción de manuscrito",
    "author": "Iaia Pilar",
    "type": "Plato tradicional",
    "family": "Sopas y cremas",
    "servings": "6-8 personas",
    "time": "1 h 15 min aprox. + cocción final",
    "difficulty": "Media",
    "status": "Pendiente de hacer",
    "ingredients": [
      "Huesos de ternera, de pollo y de caña.",
      "1 trozo de ternera.",
      "1 cuarto de pollo.",
      "1 cuarto de gallina.",
      "1/4 de pie de cerdo.",
      "1 trocito de rabo de cerdo.",
      "1 trocito de tocino.",
      "1 butifarra cruda.",
      "1 trocito de chorizo.",
      "Zanahoria.",
      "Apio, un poco.",
      "Puerro.",
      "Col, un poco.",
      "Patatas.",
      "Garbanzos, previamente hervidos.",
      "Carne picada de cerdo.",
      "1 huevo batido.",
      "Pan rallado, solo si la mezcla queda muy líquida.",
      "Harina, para enharinar."
    ],
    "steps": [
      "Pon los huesos en una olla grande con agua fría.",
      "Cuando empiece a hervir, añade las carnes.",
      "Deja cocer unos 45 min.",
      "Añade zanahoria, apio, puerro y col.",
      "Pasados unos 30 min, incorpora la pelota, la butifarra, el chorizo y las patatas.",
      "Mantén la cocción a fuego bajo-medio hasta que todo esté hecho.",
      "Añade al final los garbanzos ya hervidos."
    ],
    "presentation": "Sirve el caldo y, por separado, las carnes, la pelota, las verduras, las patatas y los garbanzos.",
    "tips": "Mantén un hervor suave para que el caldo quede limpio.",
    "notes": "",
    "tags": [
      "RecetaFamiliar",
      "IaiaPilar",
      "Escudella",
      "CocinaCatalana",
      "OllaTradicional",
      "Invierno"
    ],
    "emoji": "🍲",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0002",
    "record_type": "recipe",
    "title": "Bisqué de langostinos (Thermomix)",
    "origin": "Transcripción de texto",
    "author": "",
    "type": "Primer plato",
    "family": "Sopas y cremas",
    "servings": "6 personas",
    "time": "1 h",
    "difficulty": "Fácil",
    "status": "Excelente",
    "ingredients": [
      "500 g de langostinos.",
      "1 cubilete de aceite de oliva virgen extra.",
      "1 zanahoria.",
      "1 cebolla.",
      "1 puerro pequeño.",
      "1 diente de ajo.",
      "1 hoja de laurel.",
      "100 g de tomate.",
      "250 g de patatas cocidas.",
      "1 cubilete de vino blanco seco.",
      "1/2 cubilete de brandy.",
      "1 l de caldo de pescado.",
      "50 g de mantequilla.",
      "150 g de nata líquida.",
      "Perejil o cebollino.",
      "Sal y pimienta."
    ],
    "steps": [
      "Cuece las patatas unos 15 min y reserva.",
      "Pela los langostinos y separa colas y cabezas.",
      "Pica zanahoria, cebolla, puerro y ajo 10 s · velocidad 4.",
      "Añade aceite y rehoga 10 min · 90 °C · velocidad 1.",
      "Añade cabezas y tomate; rehoga 4 min · Varoma · velocidad 2.",
      "Añade el brandy 3 min · Varoma · velocidad 2.",
      "Agrega caldo, vino, parte de las patatas y laurel; cocina 40 min · 100 °C · velocidad 1.",
      "Retira laurel y cabezas.",
      "Tritura a velocidad progresiva 6-8-10.",
      "Añade nata, mantequilla, colas y resto de patatas; mezcla 2 min · 90 °C · velocidad cuchara."
    ],
    "presentation": "Sirve bien caliente con perejil o cebollino.",
    "tips": "No cuezas en exceso las patatas.",
    "notes": "La hago desde hace años: buenísima, no falla. Especial para Navidad.",
    "tags": [
      "Thermomix",
      "Langostinos",
      "Navidad",
      "Excelente"
    ],
    "emoji": "🍤",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0003",
    "record_type": "technique",
    "title": "Caldo base para arroces y fideuás",
    "origin": "Jordi Cruz · Transcripción de publicación en redes sociales",
    "author": "Jordi Cruz",
    "type": "Técnica culinaria",
    "family": "Técnicas y bases",
    "servings": "No indicadas",
    "time": "3 h aprox. + preparación",
    "difficulty": "Media",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1/2 costillar de cerdo.",
      "1 muslo de pollo.",
      "2 cebolletas.",
      "1-2 zanahorias.",
      "1 puerro.",
      "1 chirivía.",
      "Apio.",
      "Ajo en polvo.",
      "Hinojo en polvo.",
      "10 g de pimentón.",
      "Comino, pimienta y azafrán.",
      "2-3 ñoras.",
      "150 g de sofrito de tomate.",
      "1 cucharada de tomate concentrado.",
      "Vino blanco.",
      "Sal.",
      "Aceite de oliva.",
      "Recortes o cabezas para personalizar."
    ],
    "steps": [
      "Asa las carnes a 200-215 °C hasta dorarlas.",
      "Pocha lentamente las verduras.",
      "Añade especias y ñoras.",
      "Desglasa con vino blanco.",
      "Pasa todo a una olla y añade los tomates.",
      "Personaliza con pescado, marisco, calamar o carne.",
      "Cuece a fuego muy suave unas 3 h."
    ],
    "presentation": "Úsalo como base para arroces o fideuás.",
    "tips": "Dora bien las carnes y carameliza las verduras.",
    "notes": "",
    "tags": [
      "TecnicaCulinaria",
      "Arroces",
      "Fideuas",
      "CaldoBase"
    ],
    "emoji": "🥣",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0004",
    "record_type": "recipe",
    "title": "Magdalenas caseras de Puente Genil",
    "origin": "Gastronomía de Puente Genil · Página web · Transcripción",
    "author": "",
    "type": "Repostería",
    "family": "Repostería",
    "servings": "Unas 8 docenas",
    "time": "15-17 min + reposo",
    "difficulty": "Fácil",
    "status": "Excelente",
    "ingredients": [
      "1 kg de harina.",
      "1 kg de azúcar.",
      "12 huevos.",
      "750 ml de aceite de oliva virgen extra.",
      "250 ml de leche entera.",
      "30 g de levadura.",
      "5 sobres de gaseosa.",
      "Ralladura de 1 limón.",
      "Azúcar y canela para terminar."
    ],
    "steps": [
      "Mezcla harina, gaseosa y levadura.",
      "Bate los huevos.",
      "Añade aceite, leche, ralladura y azúcar.",
      "Incorpora la harina poco a poco.",
      "Deja reposar la masa.",
      "Llena los moldes hasta la mitad o tres cuartas partes.",
      "Espolvorea azúcar y canela.",
      "Hornea a 170 °C durante 15-17 min."
    ],
    "presentation": "Sirve templadas o frías.",
    "tips": "No llenes por completo los moldes.",
    "notes": "Mi receta favorita de magdalenas.",
    "tags": [
      "PuenteGenil",
      "Reposteria",
      "Horno",
      "Excelente",
      "RecetaFavorita"
    ],
    "emoji": "🧁",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0005",
    "record_type": "recipe",
    "title": "Helado de vainilla y nueces (Thermomix)",
    "origin": "Juani de Ana Sevilla · Página web · Transcripción",
    "author": "Juani de Ana Sevilla",
    "type": "Postre",
    "family": "Helados",
    "servings": "No indicadas",
    "time": "8 min + congelación",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "100 g de nueces.",
      "250 g de azúcar.",
      "5 gotas de limón.",
      "200 g de nata para montar.",
      "500 g de leche.",
      "5 yemas.",
      "1 cucharadita de maicena.",
      "1 vaina de vainilla.",
      "Ralladura de limón.",
      "Canela.",
      "Sal.",
      "Miel o azúcar invertido."
    ],
    "steps": [
      "Pica las nueces 5 s · velocidad 4.",
      "Caramelízalas con 100 g de azúcar y limón.",
      "Monta la nata y reserva.",
      "Mezcla leche, yemas, maicena y 150 g de azúcar 10 s · velocidad 5.",
      "Añade vainilla, ralladura, canela y sal; programa 8 min · 90 °C · velocidad 2.",
      "Añade miel y mezcla 1 min sin temperatura.",
      "Enfría, mezcla con la nata y añade las nueces.",
      "Congela y remueve cada 50 min."
    ],
    "presentation": "Sirve con la consistencia deseada.",
    "tips": "La crema debe enfriarse completamente antes de unirla con la nata.",
    "notes": "",
    "tags": [
      "Thermomix",
      "Helado",
      "Vainilla",
      "Nueces"
    ],
    "emoji": "🍨",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0006",
    "record_type": "technique",
    "title": "Marca de calamar para arroces y fideuás",
    "origin": "Jordi Cruz · Instagram · Transcripción",
    "author": "Jordi Cruz",
    "type": "Técnica culinaria",
    "family": "Técnicas y bases",
    "servings": "No indicado",
    "time": "45 min aprox.",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "2-3 cebollas.",
      "3-4 dientes de ajo.",
      "1 kg de pulpa de tomate.",
      "Calamar fresco.",
      "Aceite de oliva.",
      "Pimentón.",
      "Azafrán, pimienta y comino.",
      "Sal.",
      "1 cucharada de tomate doble concentrado."
    ],
    "steps": [
      "Limpia el calamar y reserva recortes.",
      "Saltea el calamar picado y reserva.",
      "Pocha lentamente la cebolla.",
      "Añade el ajo.",
      "Añade pimentón y especias.",
      "Reincorpora el calamar.",
      "Añade tomate, sal y concentrado.",
      "Cocina a fuego suave unos 45 min."
    ],
    "presentation": "Úsala como base de arroces y fideuás.",
    "tips": "Puede refrigerarse o congelarse. Usa aprox. 250 g por 250 g de arroz.",
    "notes": "",
    "tags": [
      "TecnicaCulinaria",
      "MarcaDeCalamar",
      "Arroces",
      "Fideua"
    ],
    "emoji": "🦑",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0007",
    "record_type": "recipe",
    "title": "Leche de almendras (Thermomix)",
    "origin": "Elaboración propia · Versión Thermomix",
    "author": "",
    "type": "Bebida",
    "family": "Técnicas y bases",
    "servings": "Aprox. 1 litro",
    "time": "10 min + 8-12 h de remojo",
    "difficulty": "Muy fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "200 g de almendras crudas peladas.",
      "1 l de agua.",
      "1 pizca de sal, opcional.",
      "1-2 dátiles o 20 g de miel, opcional.",
      "Vainilla o canela, opcional."
    ],
    "steps": [
      "Remoja las almendras 8-12 h.",
      "Escúrrelas y enjuágalas.",
      "Pon todos los ingredientes en el vaso.",
      "Tritura 2 min · velocidad 10.",
      "Cuela.",
      "Guarda en frío."
    ],
    "presentation": "Sirve fría.",
    "tips": "Se conserva 3-4 días. Agita antes de consumir.",
    "notes": "",
    "tags": [
      "Thermomix",
      "BebidaVegetal",
      "SinLactosa"
    ],
    "emoji": "🥛",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": "Puede ser vegana utilizando dátiles en lugar de miel."
  },
  {
    "id": "rtm-0008",
    "record_type": "technique",
    "title": "Adobo tradicional para costillas y cinta de lomo",
    "origin": "Elaboración propia · Versión revisada",
    "author": "",
    "type": "Adobo · Marinada",
    "family": "Técnicas y bases",
    "servings": "Para 2 kg de carne",
    "time": "Sin cocción · 12-48 h de reposo",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "2 kg de costillas o cinta de lomo.",
      "100 ml de aceite de oliva.",
      "100 ml de vino blanco.",
      "8 dientes de ajo.",
      "30 g de pimentón dulce.",
      "Pimentón picante, opcional.",
      "Orégano.",
      "Tomillo.",
      "Comino, opcional.",
      "Laurel.",
      "20 g de sal.",
      "Pimienta negra."
    ],
    "steps": [
      "Machaca ajo y sal.",
      "Añade especias.",
      "Incorpora aceite y vino.",
      "Reparte sobre la carne.",
      "Añade laurel.",
      "Refrigera 12-48 h.",
      "Da la vuelta durante el reposo.",
      "Saca 30 min antes de cocinar."
    ],
    "presentation": "Cocina al horno, parrilla, barbacoa o sartén.",
    "tips": "No superes 48 h de marinado.",
    "notes": "",
    "tags": [
      "TecnicaCulinaria",
      "Adobo",
      "Cerdo",
      "SinVinagre"
    ],
    "emoji": "🥩",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0009",
    "record_type": "recipe",
    "title": "Solomillo de cerdo con salsa de brandy y soja",
    "origin": "Red social · Transcripción",
    "author": "",
    "type": "Plato principal",
    "family": "Carne",
    "servings": "No indicadas",
    "time": "20 min de marinado + cocción",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1 solomillo de cerdo.",
      "Aceite de oliva virgen extra.",
      "Sal.",
      "Pimienta negra.",
      "Ajo en polvo.",
      "1 chupito de aceite de oliva.",
      "1 chupito de brandy.",
      "3 cucharadas de salsa de soja."
    ],
    "steps": [
      "Corta el solomillo en medallones.",
      "Mézclalo con los ingredientes de la salsa.",
      "Marina 20 min.",
      "Dora los medallones.",
      "Añade la salsa.",
      "Flambea y reduce."
    ],
    "presentation": "Sirve recién hecho con la salsa.",
    "tips": "Flambea lejos de la campana extractora.",
    "notes": "",
    "tags": [
      "Carne",
      "Solomillo",
      "Brandy",
      "SalsaDeSoja"
    ],
    "emoji": "🥩",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0010",
    "record_type": "recipe",
    "title": "Crema fría de espárragos blancos y anchoas",
    "origin": "Marta Martínez (@martamchef6, Instagram) · Transcripción",
    "author": "Marta Martínez",
    "type": "Entrante",
    "family": "Sopas y cremas",
    "servings": "2 personas",
    "time": "No indicado",
    "difficulty": "Muy fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1 lata de espárragos blancos.",
      "1 huevo duro.",
      "4 anchoas.",
      "1/2 diente de ajo.",
      "1 yogur natural."
    ],
    "steps": [
      "Introduce todos los ingredientes en la batidora.",
      "Tritura hasta obtener una crema homogénea."
    ],
    "presentation": "Sirve fría, con menta o albahaca si se desea.",
    "tips": "La fuente no indica tiempo de refrigeración.",
    "notes": "",
    "tags": [
      "CremaFria",
      "Esparragos",
      "Anchoas",
      "Verano"
    ],
    "emoji": "🥣",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0011",
    "record_type": "recipe",
    "title": "Crema fría de piquillos y garbanzos",
    "origin": "Redes sociales · Transcripción de imagen",
    "author": "",
    "type": "Entrante",
    "family": "Sopas y cremas",
    "servings": "2 personas",
    "time": "5 min",
    "difficulty": "Muy fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "300 g de pimientos del piquillo.",
      "300 g de garbanzos cocidos.",
      "1 yogur natural.",
      "1 cucharada de aceite de oliva.",
      "Sal.",
      "Pimienta.",
      "200 ml de agua fría.",
      "Huevo cocido, tomate y cebolla, opcionales."
    ],
    "steps": [
      "Pon todos los ingredientes en la batidora.",
      "Salpimienta.",
      "Tritura hasta obtener una crema fina.",
      "Refrigera."
    ],
    "presentation": "Sirve fría con huevo cocido o tomate y cebolla.",
    "tips": "La fuente no especifica conservación.",
    "notes": "",
    "tags": [
      "CremaFria",
      "Piquillos",
      "Garbanzos",
      "Rapida",
      "SinCoccion"
    ],
    "emoji": "🥣",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0012",
    "record_type": "recipe",
    "title": "Crema fría de alcachofas (Thermomix)",
    "origin": "Página web / captura de pantalla · Transcripción normalizada",
    "author": "",
    "type": "Entrante",
    "family": "Sopas y cremas",
    "servings": "4 aprox.",
    "time": "Sin cocción + refrigeración",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "2 botes de corazones de alcachofa con su líquido.",
      "3 huevos duros.",
      "150 g de cebolla tierna.",
      "1 diente de ajo.",
      "50 g de aceite de oliva.",
      "5 g de vinagre.",
      "Sal.",
      "4 lonchas de jamón serrano.",
      "Pimienta negra."
    ],
    "steps": [
      "Pon en el vaso todo excepto jamón y pimienta.",
      "Tritura 1 min 30 s · velocidad 10.",
      "Refrigera.",
      "Haz el jamón crujiente en microondas en tandas de 30 s.",
      "Desmenuza el jamón."
    ],
    "presentation": "Sirve fría con jamón crujiente, aceite y pimienta.",
    "tips": "Vigila el jamón en el microondas.",
    "notes": "",
    "tags": [
      "Thermomix",
      "Alcachofas",
      "CremaFria",
      "Verano"
    ],
    "emoji": "🥣",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0013",
    "record_type": "recipe",
    "title": "Croquetas de merluza y gambas",
    "origin": "Directo al Paladar · María Pimientos · Transcripción",
    "author": "María Pimientos",
    "type": "Aperitivo",
    "family": "Pescado",
    "servings": "6 personas",
    "time": "2 h 40 min",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "150 g de merluza.",
      "150 g de gambas.",
      "150 g de aceite de oliva.",
      "200 g de harina.",
      "1 l de fumet.",
      "Sal y pimienta.",
      "Harina, huevo y pan rallado para rebozar.",
      "Aceite para freír."
    ],
    "steps": [
      "Pela las gambas.",
      "Prepara fumet si no dispones de él.",
      "Haz un roux con harina y aceite.",
      "Añade el caldo poco a poco.",
      "Incorpora merluza y gambas.",
      "Refrigera 2 h.",
      "Forma y reboza.",
      "Fríe hasta dorar."
    ],
    "presentation": "Sirve recién hechas.",
    "tips": "La masa debe reposar 2 h.",
    "notes": "",
    "tags": [
      "Croquetas",
      "Merluza",
      "Gambas",
      "Aperitivo"
    ],
    "emoji": "🐟",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0014",
    "record_type": "recipe",
    "title": "Petit Suisse de fresas en vasitos",
    "origin": "El Forner de Alella · Página web · Transcripción",
    "author": "Josep Maria Mañé y Carme Julià",
    "type": "Postre",
    "family": "Postres",
    "servings": "6 vasitos",
    "time": "No indicado + refrigeración",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "500 g de fresas.",
      "250 g de queso crema.",
      "100 g de nata para montar.",
      "150 g de azúcar.",
      "5 g de cuajada en polvo."
    ],
    "steps": [
      "Lava y corta las fresas.",
      "Tritura y cuela.",
      "Pon en una cazuela.",
      "Añade nata, azúcar y queso crema.",
      "Incorpora la cuajada.",
      "Remueve hasta que empiece a hervir.",
      "Deja enfriar.",
      "Reparte en vasitos y refrigera."
    ],
    "presentation": "Sirve frío con media fresa y menta.",
    "tips": "Remueve continuamente durante la cocción.",
    "notes": "",
    "tags": [
      "PetitSuisse",
      "Fresas",
      "Postre",
      "Vasitos"
    ],
    "emoji": "🍓",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0015",
    "record_type": "recipe",
    "title": "Zurracapote",
    "origin": "María Jesús Gil de Antuñano · Revista · Transcripción",
    "author": "María Jesús Gil de Antuñano",
    "type": "Postre",
    "family": "Postres",
    "servings": "4 personas",
    "time": "1 h aprox. + 2 h de remojo",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "175 g de ciruelas pasas.",
      "175 g de orejones.",
      "150 g de azúcar moreno.",
      "4 vasos de vino tinto.",
      "La misma cantidad de agua.",
      "1 palo de canela.",
      "Corteza de limón.",
      "Nata líquida."
    ],
    "steps": [
      "Remoja ciruelas y orejones 2 h.",
      "Pon vino y agua en un cazo.",
      "Añade canela, azúcar y limón.",
      "Lleva a ebullición y espuma.",
      "Añade la fruta escurrida.",
      "Cuece 25-30 min."
    ],
    "presentation": "Sirve con nata líquida.",
    "tips": "Controla el punto del almíbar.",
    "notes": "",
    "tags": [
      "Postre",
      "FrutaSeca",
      "VinoTinto"
    ],
    "emoji": "🍷",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0016",
    "record_type": "recipe",
    "title": "Mousse de tres quesos",
    "origin": "María Jesús Gil de Antuñano · Revista · Transcripción",
    "author": "María Jesús Gil de Antuñano",
    "type": "Postre",
    "family": "Postres",
    "servings": "4 personas",
    "time": "1 h aprox.",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1/4 l de nata líquida.",
      "1/4 l de leche.",
      "50 g de queso Idiazábal.",
      "50 g de queso Caprice des Dieux.",
      "2 tarrinas de queso San Millán.",
      "2 huevos.",
      "200 g de azúcar."
    ],
    "steps": [
      "Hierve leche y quesos hasta fundirlos.",
      "Tritura y enfría.",
      "Monta la nata.",
      "Bate queso San Millán, huevos y azúcar.",
      "Une las mezclas.",
      "Incorpora la nata.",
      "Reparte en copas.",
      "Refrigera."
    ],
    "presentation": "Acompaña con salsa de frutos rojos y ralladura de cítricos.",
    "tips": "La nata debe estar muy fría.",
    "notes": "La cantidad de azúcar de la fuente parece elevada; pendiente de confirmar.",
    "tags": [
      "Mousse",
      "Queso",
      "Postre"
    ],
    "emoji": "🧀",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0017",
    "record_type": "recipe",
    "title": "Cocochas rebozadas",
    "origin": "María Jesús Gil de Antuñano · Revista · Transcripción",
    "author": "María Jesús Gil de Antuñano",
    "type": "Segundo plato",
    "family": "Pescado",
    "servings": "4 personas",
    "time": "30 min aprox.",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "500 g de cocochas de merluza o bacalao.",
      "2 huevos.",
      "Harina.",
      "Aceite.",
      "Sal.",
      "Pimienta.",
      "Zumo de limón.",
      "1 lata de pimientos del piquillo.",
      "1 diente de ajo.",
      "2 cucharadas de aceite.",
      "2 cucharadas de nata."
    ],
    "steps": [
      "Limpia y salpimienta las cocochas.",
      "Rocía con limón.",
      "Pasa por harina y huevo.",
      "Fríe y escurre.",
      "Dora el ajo.",
      "Rehoga los pimientos.",
      "Añade el líquido y liga.",
      "Tritura, rectifica de sal y añade nata."
    ],
    "presentation": "Sirve con la salsa de piquillos.",
    "tips": "Fríe con el aceite bien caliente.",
    "notes": "",
    "tags": [
      "Cocochas",
      "Pescado",
      "Rebozado"
    ],
    "emoji": "🐟",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0018",
    "record_type": "recipe",
    "title": "Crema de cebolla al brandy",
    "origin": "María Jesús Gil de Antuñano · Revista · Transcripción",
    "author": "María Jesús Gil de Antuñano",
    "type": "Primer plato",
    "family": "Sopas y cremas",
    "servings": "4 personas",
    "time": "1 h aprox.",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "3 cebollas.",
      "1 l de caldo de ave.",
      "2 quesitos.",
      "1 yema.",
      "6 cucharadas de aceite.",
      "1 copa de brandy.",
      "Harina.",
      "Aceite para freír.",
      "Sal.",
      "Pimienta."
    ],
    "steps": [
      "Pica dos cebollas.",
      "Estófalas 30 min.",
      "Añade brandy y flambea.",
      "Añade caldo y cuece 10 min.",
      "Tritura con quesitos.",
      "Añade la yema al final.",
      "Corta la tercera cebolla en aros.",
      "Remoja, enharina y fríe."
    ],
    "presentation": "Sirve con los aros de cebolla fritos.",
    "tips": "Flambea con precaución y añade la yema sin hervor fuerte.",
    "notes": "",
    "tags": [
      "Cebolla",
      "Brandy",
      "SopasYCremas"
    ],
    "emoji": "🧅",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0019",
    "record_type": "technique",
    "title": "Aceites aromatizados (Thermomix)",
    "origin": "Cuida tu salud con Thermomix, Vorwerk, pág. 30 · Transcripción",
    "author": "",
    "type": "Condimento",
    "family": "Técnicas y bases",
    "servings": "150-250 g aprox.",
    "time": "5 min / 30 s",
    "difficulty": "Muy fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "250 g de aceite de oliva y 2 ramitas de albahaca seca, para larga duración.",
      "1 cubilete de perejil, 1 ramita de cebollino y 150 g de aceite de oliva, para uso inmediato."
    ],
    "steps": [
      "Para larga duración, programa aceite y albahaca 5 min · 100 °C · velocidad 1.",
      "Deja infusionar y envasa.",
      "Para uso inmediato, pica perejil y cebollino 10 s · velocidad 7.",
      "Añade aceite y tritura 20 s · velocidad progresiva 5-10.",
      "Cuela."
    ],
    "presentation": "Úsalos para ensaladas, verduras, pastas, arroces, carnes y pescados.",
    "tips": "El de larga duración se conserva meses; el inmediato, aprox. una semana en frío.",
    "notes": "",
    "tags": [
      "TecnicaCulinaria",
      "Aceites",
      "Thermomix",
      "AOVE"
    ],
    "emoji": "🫒",
    "vegetarian": true,
    "vegan": true,
    "dietary_note": ""
  },
  {
    "id": "rtm-0020",
    "record_type": "recipe",
    "title": "Pa de fetge",
    "origin": "Cuines - TV3 · Página web · Transcripción",
    "author": "",
    "type": "Entrante",
    "family": "Carne y charcutería",
    "servings": "No indicadas",
    "time": "1 h 15 min + 3 h de enfriado + 2 h de remojo",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "300 g de hígado de cerdo.",
      "240 g de carne magra de cerdo.",
      "360 g de papada.",
      "100 g de cebolla.",
      "1/2 diente de ajo.",
      "2 cucharadas de mantequilla.",
      "2 huevos.",
      "18 g de sal.",
      "3 g de salitre.",
      "3 g de azúcar de caña.",
      "3 granos de pimienta negra.",
      "1 vasito de vino blanco seco.",
      "Aceite para la terrina.",
      "Pan tostado.",
      "Nueces.",
      "2 rábanos."
    ],
    "steps": [
      "Remoja el hígado 2 h.",
      "Mantén hígado, carne y papada con salitre.",
      "Pocha la cebolla con mantequilla y enfría.",
      "Mezcla carnes, sal y pimienta.",
      "Machaca el ajo y mézclalo con los huevos.",
      "Amasa todo.",
      "Añade pimienta y vino.",
      "Incorpora cebolla.",
      "Vierte en terrina aceitada.",
      "Pinta con clara.",
      "Hornea a 180 °C durante 1 h 15 min con un recipiente de agua.",
      "Enfría 3 h."
    ],
    "presentation": "Sirve con pan tostado, nueces y rábanos.",
    "tips": "Usa únicamente salitre alimentario y respeta la cantidad indicada.",
    "notes": "La fuente deja dudas sobre el uso exacto del salitre.",
    "tags": [
      "PaDeFetge",
      "Carne",
      "Charcuteria",
      "Horno",
      "CocinaCatalana"
    ],
    "emoji": "🍖",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0021",
    "record_type": "recipe",
    "title": "Coca de verduras (Thermomix)",
    "origin": "Vorwerk / Thermomix · Libro · Transcripción",
    "author": "",
    "type": "Coca salada",
    "family": "Panadería",
    "servings": "6 raciones",
    "time": "22 min",
    "difficulty": "Fácil",
    "status": "Excelente",
    "ingredients": [
      "100 g de pimiento rojo, en trozos.",
      "100 g de pimiento verde, en trozos.",
      "100 g de cebolla, en trozos.",
      "100 g de calabacín con piel, en trozos.",
      "100 g de aceite de oliva.",
      "2 cucharaditas de sal.",
      "1 cucharada de pimentón.",
      "50 g de aceite de oliva virgen extra.",
      "100 g de agua.",
      "50 g de manteca de cerdo.",
      "20 g de levadura prensada fresca de panadería.",
      "300 g de harina de fuerza.",
      "1 cucharadita de sal.",
      "1 pellizco de azúcar."
    ],
    "steps": [
      "Precalienta el horno a 200 °C.",
      "Pon en el vaso el pimiento rojo y verde, la cebolla, el calabacín, el aceite, la sal y el pimentón. Programa 3 s · velocidad 4. Retira y reserva.",
      "Sin lavar el vaso, pon el aceite, el agua y la manteca. Programa 1 min · 37 °C · velocidad 2.",
      "Incorpora la levadura, la harina, la sal y el azúcar. Mezcla 30 s · velocidad 6.",
      "Retira la masa y extiéndela muy fina sobre una bandeja de horno bien engrasada. Déjala reposar unos minutos.",
      "Cubre con las verduras reservadas y hornea durante 20 min aproximadamente."
    ],
    "presentation": "Sirve cortada en porciones, recién hecha o templada.",
    "tips": "Para una versión vegetariana, puede sustituirse la manteca por aceite de oliva.",
    "notes": "Hecha varias veces. Queda excelente.",
    "tags": [
      "Vorwerk",
      "Thermomix",
      "CocaSalada",
      "Panaderia",
      "Verduras",
      "Horno",
      "RecetaProbada",
      "Excelente"
    ],
    "emoji": "🥧",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0022",
    "record_type": "recipe",
    "title": "Crema fría de melón (Thermomix)",
    "origin": "Cristina Ferrer · Página web · Adaptación probada",
    "author": "Cristina Ferrer",
    "type": "Entrante",
    "family": "Sopas y cremas",
    "servings": "6 personas",
    "time": "5 min + frío",
    "difficulty": "Muy fácil",
    "status": "Probada",
    "ingredients": [
      "1 kg de melón maduro, en trozos.",
      "2 yogures naturales o griegos.",
      "6-7 hojas de menta fresca.",
      "Zumo de 1/2 limón.",
      "1 pellizco de sal.",
      "1 pellizco de pimienta negra.",
      "2 cucharaditas de azúcar, aproximadamente, según el dulzor del melón."
    ],
    "steps": [
      "Pon en el vaso el melón y la menta. Tritura 1 min · velocidad 10.",
      "Añade los yogures, el zumo de limón, la sal, la pimienta y el azúcar, ajustándolo al dulzor del melón.",
      "Mezcla 30 s · velocidad 4.",
      "Reserva en el frigorífico hasta que esté bien fría."
    ],
    "presentation": "Sirve muy fría.",
    "tips": "Ajusta el azúcar al dulzor de la fruta. Prepararla con antelación mejora el resultado.",
    "notes": "Hecha y muy buena. Toni añadió aproximadamente 2 cucharaditas de azúcar.",
    "tags": [
      "Thermomix",
      "SopasYCremas",
      "CremaFria",
      "Melon",
      "Verano",
      "Entrante",
      "RecetaProbada",
      "MuyBuena"
    ],
    "emoji": "🍈",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0023",
    "record_type": "recipe",
    "title": "Risotto con setas (Thermomix)",
    "origin": "Velocidad Cuchara · Página web · Transcripción",
    "author": "Rosa Ardá",
    "type": "Plato principal",
    "family": "Arroces",
    "servings": "6 personas",
    "time": "40 min",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "50 g de queso parmesano.",
      "200 g de cebolla, en cuartos.",
      "200 g de setas al gusto, en trozos.",
      "40 g de aceite de oliva virgen extra.",
      "350 g de arroz de grano corto para risotto o arroz bomba.",
      "200 g de cerveza clásica o, en su defecto, vino o caldo.",
      "650 g de caldo de verduras, muy caliente.",
      "1 cucharadita de sal.",
      "10 g de mantequilla con sal.",
      "Pimienta negra molida, opcional."
    ],
    "steps": [
      "Ralla el parmesano 10 s · velocidad progresiva 5-10. Retira y reserva.",
      "Pon la cebolla en el vaso y trocea 5 s · velocidad 4. Añade la mitad de las setas y el aceite y cocina 10 min · 120 °C o Varoma · velocidad 1.",
      "Incorpora el arroz y programa 3 min · 120 °C o Varoma · giro inverso · velocidad cuchara.",
      "Vierte la cerveza o el vino y, sin cubilete, programa 5 min · 120 °C o Varoma · giro inverso · velocidad cuchara.",
      "Añade el caldo muy caliente y la sal. Programa 8 min · 100 °C · giro inverso · velocidad cuchara.",
      "Incorpora el resto de las setas y programa 5 min · 100 °C · giro inverso · velocidad cuchara.",
      "Vuelca en una fuente, reparte la mantequilla y espolvorea el parmesano."
    ],
    "presentation": "Sirve recién hecho.",
    "tips": "El caldo debe estar muy caliente.",
    "notes": "",
    "tags": [
      "VelocidadCuchara",
      "RosaArda",
      "Arroces",
      "Risotto",
      "Setas",
      "Thermomix",
      "PendienteDeHacer"
    ],
    "emoji": "🍚",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0024",
    "record_type": "recipe",
    "title": "Capipota de Ada Parellada",
    "origin": "Página web · Transcripción",
    "author": "Ada Parellada",
    "type": "Plato tradicional",
    "family": "Carne",
    "servings": "No indicadas",
    "time": "40 min de cocción final",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1 kg de capipota cocido.",
      "150 g de tocino.",
      "2 cebollas.",
      "5 tomates de rama.",
      "3 dientes de ajo.",
      "1 guindilla.",
      "60 g de jamón en dados.",
      "1/2 cucharada de pimentón dulce.",
      "1 vaso de brandy.",
      "500 ml de caldo de pollo o agua.",
      "200 g de judías hervidas.",
      "Aceite.",
      "Sal.",
      "Avellanas tostadas, un puñado.",
      "Perejil.",
      "2 galletas."
    ],
    "steps": [
      "Pon el tocino en una cazuela con aceite y deja que sude hasta dorarse.",
      "Añade la cebolla y cocina muy lentamente con sal.",
      "Incorpora los tomates rallados y cocina hasta obtener un sofrito de color de mermelada.",
      "Añade ajo, guindilla, jamón, capipota, pimentón y brandy.",
      "Deja evaporar el brandy y cubre con caldo o agua.",
      "Prepara una picada con avellanas, perejil, galletas y sal.",
      "Añade la picada y cocina unos 40 min.",
      "Incorpora las judías y ajusta de sal."
    ],
    "presentation": "Sirve caliente.",
    "tips": "Cocina el sofrito muy lentamente.",
    "notes": "",
    "tags": [
      "AdaParellada",
      "Capipota",
      "PlatoTradicional",
      "Carne",
      "CocinaCatalana",
      "Cazuela",
      "PendienteDeHacer"
    ],
    "emoji": "🥘",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0025",
    "record_type": "recipe",
    "title": "Mayonesa casera y variaciones sencillas",
    "origin": "Directo al Paladar · Página web · Transcripción",
    "author": "Pakus",
    "type": "Salsa",
    "family": "Técnicas y bases",
    "servings": "No indicado",
    "time": "No indicado",
    "difficulty": "Fácil",
    "status": "Probada",
    "ingredients": [
      "1 huevo M, a temperatura ambiente.",
      "4 g de sal.",
      "10 g de vinagre o zumo de limón, a temperatura ambiente.",
      "200 ml de aceite vegetal, de oliva o mezcla, a temperatura ambiente."
    ],
    "steps": [
      "Casca el huevo en un recipiente aparte y pásalo al vaso de la batidora.",
      "Añade la sal, el vinagre o limón y la mitad del aceite.",
      "Coloca la batidora tocando el fondo y bate a potencia baja sin moverla hasta que emulsione.",
      "Incorpora el resto del aceite y levanta la batidora mientras sigues batiendo hasta obtener el espesor deseado."
    ],
    "presentation": "Sirve como salsa o acompañamiento.",
    "tips": "Mantén los ingredientes a temperatura ambiente y extrema la higiene con el huevo crudo.",
    "notes": "Variantes documentadas: curry, japonesa, especias, wasabi, ajonesa, ajo negro, lima y picante con miel y Tabasco.",
    "tags": [
      "PaginaWeb",
      "Salsa",
      "TecnicasYBases",
      "Mayonesa",
      "Batidora",
      "Probada"
    ],
    "emoji": "🥣",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0026",
    "record_type": "recipe",
    "title": "Kebab casero en brocheta con salsa de yogur (Air fryer)",
    "origin": "Jozichef (redes sociales) · Adaptación con salsa de yogur",
    "author": "Jozichef",
    "type": "Plato principal",
    "family": "Carne",
    "servings": "No indicadas",
    "time": "15 min de cocción + preparación",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "4 tortillas de trigo.",
      "500 g de carne picada mixta (ternera y cerdo).",
      "Queso rallado para fundir, cantidad no indicada.",
      "Sal.",
      "Pimienta negra.",
      "Pimentón.",
      "Orégano.",
      "Aceite de oliva en espray.",
      "Palillos de brocheta.",
      "1 yogur griego natural (125 g).",
      "1 diente de ajo pequeño, rallado.",
      "1 cucharada de zumo de limón.",
      "1 cucharada de aceite de oliva virgen extra.",
      "1 cucharada de perejil o menta, picados."
    ],
    "steps": [
      "Mezcla la carne con sal, pimienta, pimentón y orégano.",
      "Da forma rectangular a las tortillas.",
      "Extiende sobre cada tortilla una capa fina de carne y espolvorea queso.",
      "Superpone las tortillas hasta formar una torre.",
      "Corta la torre en 4 tiras iguales.",
      "Superpone las tiras formando un bloque.",
      "Atraviesa con palillos de brocheta y corta entre ellos.",
      "Rocía con aceite.",
      "Cocina en air fryer a 195 °C durante 15 min, comprobando que la carne esté completamente cocinada.",
      "Mezcla los ingredientes de la salsa de yogur y reserva en frío."
    ],
    "presentation": "Sirve las brochetas recién hechas con la salsa aparte.",
    "tips": "El tiempo puede variar según la air fryer. Comprueba especialmente el centro.",
    "notes": "",
    "tags": [
      "Jozichef",
      "Carne",
      "Kebab",
      "Brochetas",
      "AirFryer",
      "Queso",
      "SalsaDeYogur",
      "PendienteDeHacer"
    ],
    "emoji": "🥙",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0027",
    "record_type": "recipe",
    "title": "Bunyols de bacallà",
    "origin": "Arnau M. (@arnaumchef9) · Instagram · Transcripció d’imatges",
    "author": "Arnau M.",
    "type": "Aperitiu",
    "family": "Pescado",
    "servings": "No indicadas",
    "time": "No indicado",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "250 g de bacalao desalado y desmigado.",
      "250 ml de leche.",
      "80 g de mantequilla.",
      "150 g de harina floja.",
      "3 huevos medianos.",
      "2 dientes de ajo.",
      "Perejil fresco picado.",
      "1 cucharadita de levadura química.",
      "Pimienta negra.",
      "Ralladura de limón.",
      "Aceite suave, para freír."
    ],
    "steps": [
      "Funde la mantequilla en una cazuela.",
      "Añade la leche y lleva a ebullición.",
      "Incorpora la harina de golpe y remueve enérgicamente.",
      "Trabaja la masa hasta que quede homogénea y compacta.",
      "Retira del fuego y añade los huevos uno a uno.",
      "Añade el bacalao, ajo y perejil.",
      "Incorpora ralladura de limón, levadura y pimienta.",
      "Forma los buñuelos con dos cucharas y fríelos en aceite caliente.",
      "Gíralos para dorarlos por todos los lados y escurre sobre papel absorbente."
    ],
    "presentation": "Sirve recién hechos con ralladura de limón.",
    "tips": "Incorpora los huevos fuera del fuego y con la masa templada.",
    "notes": "",
    "tags": [
      "Bunyols",
      "Bacalla",
      "Pescado",
      "CocinaCatalana",
      "Aperitivo",
      "Fritos",
      "Instagram",
      "PendienteDeHacer"
    ],
    "emoji": "🐟",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0028",
    "record_type": "recipe",
    "title": "Pollo en pepitoria",
    "origin": "Fotografía (cocinaconnoelia) · Adaptación",
    "author": "cocinaconnoelia",
    "type": "Plato principal",
    "family": "Carne",
    "servings": "No indicado",
    "time": "1 h 15 min aprox.",
    "difficulty": "Media",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1 pollo troceado.",
      "30 g de almendras tostadas.",
      "200 ml de vino blanco.",
      "200 ml de caldo de pollo, preferiblemente casero.",
      "2 huevos.",
      "2 dientes de ajo.",
      "1 rebanada de pan.",
      "1 cebolla.",
      "Perejil fresco.",
      "Hebras de azafrán, ligeramente tostadas.",
      "Manteca de cerdo o aceite de oliva.",
      "Sal.",
      "Pimienta."
    ],
    "steps": [
      "Cuece los huevos 10 min desde que hierva el agua. Enfría, pela y separa yemas y claras.",
      "Salpimienta el pollo y dóralo. Retira y reserva.",
      "Cocina la cebolla a fuego bajo 20-25 min hasta tierna y dorada.",
      "Tuesta el pan con aceite.",
      "Haz un majado con ajo, sal, perejil, almendras, yemas, azafrán y pan frito.",
      "Devuelve el pollo, incorpora el majado y cocina 1 min.",
      "Añade el vino y hierve 2-3 min.",
      "Añade el caldo, tapa parcialmente y cuece a fuego bajo 40-45 min."
    ],
    "presentation": "Sirve con salsa ligada, claras troceadas, almendras y perejil.",
    "tips": "Deja reposar 30 min antes de servir; ajusta con caldo si espesa demasiado.",
    "notes": "",
    "tags": [
      "PlatoPrincipal",
      "Carne",
      "Pollo",
      "Pepitoria",
      "CocinaTradicional",
      "Cazuela",
      "Almendras",
      "Azafran",
      "PendienteDeHacer"
    ],
    "emoji": "🍗",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0029",
    "record_type": "recipe",
    "title": "Bacalao dorado o Bacalhau à Brás",
    "origin": "Velocidad Cuchara · Página web · Transcripción",
    "author": "Rosa Ardá",
    "type": "Entrante / primer plato",
    "family": "Pescado",
    "servings": "6 personas",
    "time": "35 min",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "400-500 g de bacalao desalado desmigado.",
      "400 g de cebolla en juliana.",
      "1 diente de ajo picado.",
      "100 ml de aceite de oliva virgen extra.",
      "5-6 huevos medianos.",
      "40 ml de nata, opcional.",
      "200 g de patatas paja.",
      "80 g de aceitunas negras.",
      "Perejil picado."
    ],
    "steps": [
      "Pon la mariposa en el vaso, añade cebolla, ajo y aceite y cocina 16 min · 120 °C o Varoma · velocidad 1.",
      "Añade el bacalao desalado y cocina 3 min · Varoma · giro inverso · velocidad 1.",
      "Continúa la elaboración con huevos, patatas paja y acabado según la receta de origen."
    ],
    "presentation": "Termina con aceitunas negras y perejil.",
    "tips": "La fuente indica que no añade sal inicialmente por la sal del bacalao y las patatas; prueba antes de ajustar.",
    "notes": "",
    "tags": [
      "VelocidadCuchara",
      "RosaArda",
      "Bacalao",
      "CocinaPortuguesa",
      "Thermomix",
      "PendienteDeHacer"
    ],
    "emoji": "🐟",
    "vegetarian": false,
    "vegan": false,
    "dietary_note": ""
  },
  {
    "id": "rtm-0030",
    "record_type": "recipe",
    "title": "Yogur de avellana (Thermomix)",
    "origin": "Instagram (@twogaypapas) · Transcripción",
    "author": "@twogaypapas",
    "type": "Desayuno / merienda",
    "family": "Lácteos y fermentados",
    "servings": "No indicado",
    "time": "6 min + 10-12 h + refrigeración",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1,5 l de leche fresca.",
      "180 g de yogur natural, elaborado solo con leche y fermentos.",
      "Azúcar o edulcorante al gusto.",
      "100 g de avellanas tostadas, sin sal y sin piel.",
      "Semillas de chía."
    ],
    "steps": [
      "Pon 50 g de avellanas en el vaso y tritura a vel. 7-8, repitiendo varias veces y bajando los restos de las paredes, hasta conseguir una pasta fluida.",
      "Añade los otros 50 g de avellanas y tritura 4 s · vel. 4 para dejar pequeños trozos crujientes.",
      "Añade la leche, el yogur natural y el azúcar o edulcorante al gusto.",
      "Programa 6 min · 50 °C · vel. 3.",
      "Mientras se calienta, pon 1/2 cucharadita de semillas de chía en el fondo de cada vasito de cristal.",
      "Precalienta el horno a 50 °C, con calor arriba y abajo.",
      "Reparte la mezcla en los vasitos y cúbrelos con un paño limpio.",
      "Apaga el horno, introduce los vasitos y déjalos fermentar entre 10 y 12 h sin abrir el horno.",
      "Al día siguiente, tapa los vasitos y pásalos a la nevera para que cojan cuerpo."
    ],
    "presentation": "Sirve el yogur frío después de su refrigeración.",
    "tips": "Utiliza un yogur natural que contenga únicamente leche y fermentos. Para 1 l de leche, la fuente indica usar 120 g de yogur. Durante la fermentación, mantén el horno apagado y no lo abras. Conservación no especificada; pendiente de confirmar.",
    "notes": "",
    "tags": [
      "Desayuno",
      "LacteosYFermentados",
      "Yogur",
      "Avellana",
      "Thermomix",
      "Fermentacion",
      "Chia",
      "Instagram",
      "PendienteDeHacer",
      "Vegetariana"
    ],
    "emoji": "🥛",
    "vegetarian": true,
    "vegan": false,
    "dietary_note": ""
  }
];
