window.RECIPES = [
  {
    id:"rtm-0001",record_type:"recipe",title:"Escudella i carn d'olla – Iaia Pilar",
    origin:"Receta familiar · Transcripción de manuscrito",author:"Iaia Pilar",
    type:"Plato tradicional",family:"Sopas y cremas",servings:"6-8 personas",
    time:"1 h 15 min aprox. + cocción final",difficulty:"Media",status:"Pendiente de hacer",
    ingredients:["Huesos de ternera, de pollo y de caña.","1 trozo de ternera.","1 cuarto de pollo.","1 cuarto de gallina.","1/4 de pie de cerdo.","1 trocito de rabo de cerdo.","1 trocito de tocino.","1 butifarra cruda.","1 trocito de chorizo.","Zanahoria.","Apio, un poco.","Puerro.","Col, un poco.","Patatas.","Garbanzos, previamente hervidos.","Carne picada de cerdo.","1 huevo batido.","Pan rallado, solo si la mezcla queda muy líquida.","Harina, para enharinar."],
    steps:["Pon los huesos de ternera, pollo y caña en una olla grande con agua fría.","Cuando el agua empiece a hervir, añade la ternera, el pollo, la gallina, el pie de cerdo, el tocino y el rabo de cerdo.","Deja cocer durante unos 45 min.","Añade la zanahoria, el apio, el puerro y la col. Reserva las patatas para más adelante.","Pasados unos 30 min, incorpora la pelota, la butifarra, el trocito de chorizo y las patatas.","Mantén la cocción a fuego bajo-medio hasta que las carnes, la pelota y las patatas estén hechas.","Al final, añade los garbanzos ya hervidos y deja que se calienten con el conjunto."],
    presentation:"Sirve el caldo y, por separado o en una fuente, las carnes, la pelota, las verduras, las patatas y los garbanzos.",
    tips:"Mantén un hervor suave para que el caldo quede limpio. Incorpora los garbanzos al final porque ya están cocidos.",
    notes:"",tags:["RecetaFamiliar","PlatoTradicional","Escudella","CarnDOlla","CocinaCatalana","OllaTradicional","Invierno"],emoji:"🍲"
  },
  {
    id:"rtm-0002",record_type:"recipe",title:"Bisqué de langostinos (Thermomix)",origin:"Transcripción de texto",author:"",
    type:"Primer plato",family:"Sopas y cremas",servings:"6 personas",time:"1 h",difficulty:"Fácil",status:"Excelente",
    ingredients:["500 g de langostinos.","1 cubilete de aceite de oliva virgen extra.","1 zanahoria.","1 cebolla.","1 puerro pequeño, solo la parte blanca.","1 diente de ajo.","1 hoja de laurel.","100 g de tomate.","250 g de patatas cocidas.","1 cubilete de vino blanco seco.","1/2 cubilete de brandy.","1 l de caldo de pescado.","50 g de mantequilla.","150 g de nata líquida.","Perejil o cebollino.","Sal y pimienta."],
    steps:["Pela las patatas, córtalas en dados y cuécelas durante unos 15 min. Reserva.","Pela los langostinos. Reserva las colas y las cabezas por separado.","Pon en el vaso la zanahoria, la cebolla, el puerro y el ajo. Pica 10 s · velocidad 4.","Baja los restos, añade el aceite y rehoga 10 min · 90 °C · velocidad 1.","Incorpora las cabezas de los langostinos y el tomate. Rehoga 4 min · Varoma · velocidad 2.","Añade el brandy y programa 3 min · Varoma · velocidad 2.","Agrega el caldo, el vino, parte de las patatas y el laurel. Cocina 40 min · 100 °C · velocidad 1.","Retira el laurel y las cabezas.","Tritura a velocidad progresiva 6-8-10.","Añade la nata, la mantequilla, las colas y el resto de las patatas. Mezcla 2 min · 90 °C · velocidad cuchara.","Deja reposar unos minutos antes de servir."],
    presentation:"Sirve bien caliente con perejil o cebollino.",tips:"No cuezas en exceso las patatas.",notes:"Receta que Toni prepara desde hace años y que no falla en Navidad.",tags:["Thermomix","Navidad","Langostinos","SopasYCremas","Excelente"],emoji:"🍤"
  },
  {
    id:"rtm-0003",record_type:"technique",title:"Caldo base para arroces",origin:"Ficha pendiente de completar",author:"",
    type:"Base culinaria",family:"Técnicas y bases",servings:"No indicado",time:"No indicado",difficulty:"No indicada",status:"Pendiente de completar",
    ingredients:["Contenido pendiente de incorporar desde la ficha normalizada."],steps:["Contenido pendiente de incorporar desde la ficha normalizada."],presentation:"",tips:"",notes:"",tags:["TecnicaCulinaria","Arroces","CaldoBase"],emoji:"🥣"
  },
  {
    id:"rtm-0004",record_type:"recipe",title:"Magdalenas caseras de Puente Genil",origin:"Gastronomía de Puente Genil · Página web · Transcripción",author:"",
    type:"Repostería",family:"Repostería",servings:"Unas 8 docenas",time:"15-17 min + reposo",difficulty:"Fácil",status:"Excelente",
    ingredients:["1 kg de harina.","1 kg de azúcar.","12 huevos.","750 ml de aceite de oliva virgen extra.","250 ml de leche entera.","2 sobres de levadura, 30 g en total.","5 sobres de gaseosa.","Ralladura de 1 limón.","3 cucharadas de azúcar, para terminar.","Canela molida, para terminar."],
    steps:["Mezcla la harina con los sobres de gaseosa y la levadura.","Bate los huevos en otro recipiente.","Añade el aceite, la leche, la ralladura de limón y el azúcar, y continúa batiendo.","Incorpora poco a poco la mezcla de harina, sin dejar de batir, hasta que desaparezcan los grumos.","Deja reposar la masa. La fuente indica que puede reposar incluso durante toda la noche para que fermente.","Mezcla en un cuenco 3 cucharadas de azúcar con canela molida.","Reparte la masa en moldes de papel, llenándolos hasta la mitad o tres cuartas partes.","Espolvorea cada magdalena con un poco de la mezcla de azúcar y canela.","Precalienta el horno a 170 °C.","Hornea durante 15-17 min, hasta que estén doradas.","Saca las magdalenas del horno y déjalas templar antes de servir."],
    presentation:"Sirve las magdalenas templadas o frías. Recién hechas también están especialmente buenas.",tips:"El reposo prolongado es opcional según la fuente. No llenes por completo los moldes para dejar espacio a que la masa suba.",notes:"Mi receta favorita de magdalenas.",tags:["PuenteGenil","Transcripcion","Reposteria","Magdalenas","Horno","Probada","Excelente","RecetaFavorita"],emoji:"🧁"
  },
  {
    id:"rtm-0005",record_type:"recipe",title:"Helado de vainilla y nueces (Thermomix)",origin:"Juani de Ana Sevilla · Transcripción de página web",author:"Juani de Ana Sevilla",
    type:"Postre",family:"Helados",servings:"No indicadas",time:"8 min + congelación",difficulty:"No indicada",status:"Pendiente de hacer",
    ingredients:["100 g de nueces.","250 g de azúcar (100 g + 150 g).","5 gotas de zumo de limón.","200 g de nata para montar, fría.","500 g de leche.","5 yemas de huevo.","1 cucharadita de postre de maicena.","1 vaina de vainilla.","Ralladura de 1/4 de limón.","1 pizca de canela.","1 pizca de sal.","1 cucharadita de postre de miel o azúcar invertido."],
    steps:["Pon las nueces en el vaso y pícalas 5 s · velocidad 4.","Pasa las nueces a una sartén. Añade 100 g de azúcar y las gotas de limón. Cocina removiendo hasta que adquieran un color caramelo.","Extiéndelas sobre papel de horno, sepáralas y, cuando estén frías, rómpelas en trocitos pequeños. Reserva.","Coloca la mariposa. Monta la nata unos segundos · velocidad 3,5. Retira y reserva en la nevera.","Quita la mariposa. Sin lavar el vaso, añade la leche, las yemas, la maicena y los 150 g de azúcar restantes. Mezcla 10 s · velocidad 5.","Coloca de nuevo la mariposa. Añade la vaina de vainilla abierta transversalmente, la ralladura de limón, la canela y la sal. Programa 8 min · 90 °C · velocidad 2.","Añade la miel o el azúcar invertido y programa 1 min · sin temperatura · velocidad 2. Deja enfriar por completo.","Retira la vaina. Une la crema fría con la nata mediante movimientos envolventes. Incorpora las nueces caramelizadas.","Lleva la mezcla al congelador. Remueve cada 50 min para distribuir bien las nueces, hasta que esté casi congelada."],
    presentation:"Sirve el helado cuando haya alcanzado la consistencia deseada.",tips:"La nata debe estar bien fría. Deja enfriar completamente la crema antes de unirla con la nata. Remueve cada 50 min durante la congelación.",notes:"",tags:["PaginaWeb","Transcripcion","Postre","Helados","Vainilla","Nueces","Thermomix","PendienteDeHacer"],emoji:"🍨"
  },
  {
    id:"rtm-0006",record_type:"technique",title:"Marca de calamar para arroces y fideuás",origin:"Jordi Cruz · Transcripción de publicación en Instagram",author:"Jordi Cruz",
    type:"Técnica culinaria",family:"Técnicas y bases",servings:"No indicado",time:"45 min aprox.",difficulty:"No indicada",status:"Pendiente de hacer",
    ingredients:["2-3 cebollas tipo Figueras o cebolla seca.","3-4 dientes de ajo.","1 kg de pulpa de tomate.","Calamar fresco.","Aceite de oliva.","Pimentón.","Mezcla de especias para arroces: azafrán, pimienta y comino.","Sal.","1 cucharada de tomate doble concentrado."],
    steps:["Limpia el calamar y reserva las pieles, aletas y recortes para enriquecer un caldo de pescado.","Pica finamente el tubo del calamar y saltéalo en una sartén muy caliente con un poco de aceite hasta que empiece a secarse y tomar color. Reserva.","Añade aceite si es necesario y cocina lentamente la cebolla picada.","Cuando la cebolla esté aproximadamente a medio pochar, incorpora el ajo picado y continúa cocinando hasta que quede muy tierna y prácticamente transparente.","Añade el pimentón y la mezcla de especias para arroces. Sofríe solo unos segundos.","Incorpora de nuevo el calamar y mezcla bien con el sofrito.","Añade la pulpa de tomate, ajusta de sal e incorpora la cucharada de tomate doble concentrado.","Cocina a fuego suave durante unos 45 min, parcialmente tapado, hasta obtener una marca concentrada, melosa y llena de sabor."],
    presentation:"No se sirve como plato independiente. Se utiliza como base para arroces y fideuás.",tips:"Puede prepararse con antelación, refrigerarse o congelarse. Jordi Cruz recomienda aproximadamente 250 g de marca por cada 250 g de arroz o por cada 500 g de fideos.",notes:"",tags:["Transcripcion","TecnicasYBases","MarcaDeCalamar","Arroces","Fideua","Sofrito","Calamar","CocinaMediterranea","PendienteDeHacer"],emoji:"🦑"
  },
  {
    id:"rtm-0007",record_type:"recipe",title:"Leche de almendras (Thermomix)",origin:"Elaboración propia · Versión Thermomix",author:"",
    type:"Bebida",family:"Técnicas y bases",servings:"Aprox. 1 litro",time:"10 min + 8-12 h de remojo",difficulty:"Muy fácil",status:"Pendiente de hacer",
    ingredients:["200 g de almendras crudas peladas.","1 l de agua.","1 pizca de sal, opcional.","1-2 dátiles deshuesados o 20 g de miel, opcional.","1 cucharadita de extracto de vainilla o 1/2 cucharadita de canela, opcional."],
    steps:["Pon las almendras en remojo durante 8-12 horas.","Escúrrelas y enjuágalas con agua fría.","Introduce en el vaso las almendras, el agua y, si lo deseas, la sal, el endulzante y la vainilla o la canela.","Tritura 2 min · velocidad 10.","Cuela la mezcla con una bolsa para bebidas vegetales, un paño fino o un colador muy tupido.","Guarda la leche en una botella de cristal en el frigorífico."],
    presentation:"Sirve fría. También puede utilizarse para cafés, batidos, cereales o recetas de repostería.",tips:"Se conserva 3-4 días en el frigorífico. Agita antes de consumir. La pulpa puede aprovecharse en galletas, bizcochos, granola o masas de pan. Para una bebida más cremosa, utiliza 800 ml de agua; para una versión más ligera, hasta 1,2 l.",notes:"",tags:["Thermomix","LecheDeAlmendras","BebidaVegetal","TecnicasYBases","Desayuno","HechoEnCasa","SinLactosa","PendienteDeHacer"],emoji:"🥛"
  },
  {
    id:"rtm-0008",record_type:"technique",title:"Adobo tradicional para costillas y cinta de lomo",origin:"Elaboración propia · Versión revisada",author:"",
    type:"Adobo · Marinada",family:"Técnicas y bases",servings:"Para 2 kg de carne",time:"Sin cocción · 12-48 h de reposo",difficulty:"Fácil",status:"Pendiente de hacer",
    ingredients:["2 kg de costillas de cerdo o cinta de lomo.","100 ml de aceite de oliva virgen extra.","100 ml de vino blanco seco.","8 dientes de ajo.","30 g de pimentón dulce de La Vera.","3-5 g de pimentón picante, opcional.","2 cucharaditas de orégano seco.","1 cucharadita de tomillo seco.","1 cucharadita rasa de comino molido, opcional.","2 hojas de laurel troceadas.","20 g de sal.","1 cucharadita de pimienta negra molida."],
    steps:["Pela los ajos y machácalos con la sal hasta obtener una pasta.","Añade el pimentón dulce, el pimentón picante, el orégano, el tomillo, el comino y la pimienta. Mezcla bien.","Incorpora poco a poco el aceite y el vino blanco. Remueve hasta obtener un adobo homogéneo.","Coloca la carne en un recipiente apto para alimentos y reparte el adobo por toda la superficie.","Masajea bien cada pieza para que quede completamente impregnada y añade el laurel.","Tapa y deja reposar en la nevera: costillas o lomo en filetes, 12-24 h; cinta de lomo entera, 24-48 h.","Da la vuelta a la carne una o dos veces durante el reposo.","Saca la carne de la nevera 30 min antes de cocinarla y retira el exceso de adobo para evitar que el pimentón se queme."],
    presentation:"Cocina la carne al horno, a la parrilla, a la barbacoa o en sartén, según el corte elegido.",tips:"El vino blanco aporta aroma sin la acidez del vinagre. No superes las 48 h de marinado. La carne puede congelarse ya adobada. Evita las llamas directas para que no se queme el pimentón.",notes:"",tags:["ElaboracionPropia","Carne","Adobo","Cerdo","Costillas","CintaDeLomo","Marinado","SinVinagre","PendienteDeHacer"],emoji:"🥩"
  }
];
