// Recetario Toni Merino · Sprint 2.2 · 20 fichas
window.RECIPES = [
  {
    "id": "rtm-0001",
    "record_type": "recipe",
    "title": "Escudella i carn d'olla – Iaia Pilar",
    "origin": "Receta familiar · Transcripción de manuscrito",
    "author": "Iaia Pilar",
    "type": "Plato tradicional",
    "family": "Sopas y cremas",
    "servings": "6-8 personas",
    "time": "1 h 15 min aprox. + cocción final",
    "difficulty": "Media",
    "status": "Pendiente de hacer",
    "ingredients": [
      "Huesos de ternera, de pollo y de caña.",
      "1 trozo de ternera.",
      "1 cuarto de pollo.",
      "1 cuarto de gallina.",
      "1/4 de pie de cerdo.",
      "1 trocito de rabo de cerdo.",
      "1 trocito de tocino.",
      "1 butifarra cruda.",
      "1 trocito de chorizo.",
      "Zanahoria.",
      "Apio, un poco.",
      "Puerro.",
      "Col, un poco.",
      "Patatas.",
      "Garbanzos, previamente hervidos.",
      "Carne picada de cerdo.",
      "1 huevo batido.",
      "Pan rallado, solo si la mezcla queda muy líquida.",
      "Harina, para enharinar."
    ],
    "steps": [
      "Pon los huesos en una olla grande con agua fría.",
      "Cuando empiece a hervir, añade las carnes.",
      "Deja cocer unos 45 min.",
      "Añade zanahoria, apio, puerro y col.",
      "Pasados unos 30 min, incorpora la pelota, la butifarra, el chorizo y las patatas.",
      "Mantén la cocción a fuego bajo-medio hasta que todo esté hecho.",
      "Añade al final los garbanzos ya hervidos."
    ],
    "presentation": "Sirve el caldo y, por separado, las carnes, la pelota, las verduras, las patatas y los garbanzos.",
    "tips": "Mantén un hervor suave para que el caldo quede limpio.",
    "notes": "",
    "tags": [
      "RecetaFamiliar",
      "IaiaPilar",
      "Escudella",
      "CocinaCatalana",
      "OllaTradicional",
      "Invierno"
    ],
    "emoji": "🍲"
  },
  {
    "id": "rtm-0002",
    "record_type": "recipe",
    "title": "Bisqué de langostinos (Thermomix)",
    "origin": "Transcripción de texto",
    "author": "",
    "type": "Primer plato",
    "family": "Sopas y cremas",
    "servings": "6 personas",
    "time": "1 h",
    "difficulty": "Fácil",
    "status": "Excelente",
    "ingredients": [
      "500 g de langostinos.",
      "1 cubilete de aceite de oliva virgen extra.",
      "1 zanahoria.",
      "1 cebolla.",
      "1 puerro pequeño.",
      "1 diente de ajo.",
      "1 hoja de laurel.",
      "100 g de tomate.",
      "250 g de patatas cocidas.",
      "1 cubilete de vino blanco seco.",
      "1/2 cubilete de brandy.",
      "1 l de caldo de pescado.",
      "50 g de mantequilla.",
      "150 g de nata líquida.",
      "Perejil o cebollino.",
      "Sal y pimienta."
    ],
    "steps": [
      "Cuece las patatas unos 15 min y reserva.",
      "Pela los langostinos y separa colas y cabezas.",
      "Pica zanahoria, cebolla, puerro y ajo 10 s · velocidad 4.",
      "Añade aceite y rehoga 10 min · 90 °C · velocidad 1.",
      "Añade cabezas y tomate; rehoga 4 min · Varoma · velocidad 2.",
      "Añade el brandy 3 min · Varoma · velocidad 2.",
      "Agrega caldo, vino, parte de las patatas y laurel; cocina 40 min · 100 °C · velocidad 1.",
      "Retira laurel y cabezas.",
      "Tritura a velocidad progresiva 6-8-10.",
      "Añade nata, mantequilla, colas y resto de patatas; mezcla 2 min · 90 °C · velocidad cuchara."
    ],
    "presentation": "Sirve bien caliente con perejil o cebollino.",
    "tips": "No cuezas en exceso las patatas.",
    "notes": "La hago desde hace años: buenísima, no falla. Especial para Navidad.",
    "tags": [
      "Thermomix",
      "Langostinos",
      "Navidad",
      "Excelente"
    ],
    "emoji": "🍤"
  },
  {
    "id": "rtm-0003",
    "record_type": "technique",
    "title": "Caldo base para arroces y fideuás",
    "origin": "Jordi Cruz · Transcripción de publicación en redes sociales",
    "author": "Jordi Cruz",
    "type": "Técnica culinaria",
    "family": "Técnicas y bases",
    "servings": "No indicadas",
    "time": "3 h aprox. + preparación",
    "difficulty": "Media",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1/2 costillar de cerdo.",
      "1 muslo de pollo.",
      "2 cebolletas.",
      "1-2 zanahorias.",
      "1 puerro.",
      "1 chirivía.",
      "Apio.",
      "Ajo en polvo.",
      "Hinojo en polvo.",
      "10 g de pimentón.",
      "Comino, pimienta y azafrán.",
      "2-3 ñoras.",
      "150 g de sofrito de tomate.",
      "1 cucharada de tomate concentrado.",
      "Vino blanco.",
      "Sal.",
      "Aceite de oliva.",
      "Recortes o cabezas para personalizar."
    ],
    "steps": [
      "Asa las carnes a 200-215 °C hasta dorarlas.",
      "Pocha lentamente las verduras.",
      "Añade especias y ñoras.",
      "Desglasa con vino blanco.",
      "Pasa todo a una olla y añade los tomates.",
      "Personaliza con pescado, marisco, calamar o carne.",
      "Cuece a fuego muy suave unas 3 h."
    ],
    "presentation": "Úsalo como base para arroces o fideuás.",
    "tips": "Dora bien las carnes y carameliza las verduras.",
    "notes": "",
    "tags": [
      "TecnicaCulinaria",
      "Arroces",
      "Fideuas",
      "CaldoBase"
    ],
    "emoji": "🥣"
  },
  {
    "id": "rtm-0004",
    "record_type": "recipe",
    "title": "Magdalenas caseras de Puente Genil",
    "origin": "Gastronomía de Puente Genil · Página web · Transcripción",
    "author": "",
    "type": "Repostería",
    "family": "Repostería",
    "servings": "Unas 8 docenas",
    "time": "15-17 min + reposo",
    "difficulty": "Fácil",
    "status": "Excelente",
    "ingredients": [
      "1 kg de harina.",
      "1 kg de azúcar.",
      "12 huevos.",
      "750 ml de aceite de oliva virgen extra.",
      "250 ml de leche entera.",
      "30 g de levadura.",
      "5 sobres de gaseosa.",
      "Ralladura de 1 limón.",
      "Azúcar y canela para terminar."
    ],
    "steps": [
      "Mezcla harina, gaseosa y levadura.",
      "Bate los huevos.",
      "Añade aceite, leche, ralladura y azúcar.",
      "Incorpora la harina poco a poco.",
      "Deja reposar la masa.",
      "Llena los moldes hasta la mitad o tres cuartas partes.",
      "Espolvorea azúcar y canela.",
      "Hornea a 170 °C durante 15-17 min."
    ],
    "presentation": "Sirve templadas o frías.",
    "tips": "No llenes por completo los moldes.",
    "notes": "Mi receta favorita de magdalenas.",
    "tags": [
      "PuenteGenil",
      "Reposteria",
      "Horno",
      "Excelente",
      "RecetaFavorita"
    ],
    "emoji": "🧁"
  },
  {
    "id": "rtm-0005",
    "record_type": "recipe",
    "title": "Helado de vainilla y nueces (Thermomix)",
    "origin": "Juani de Ana Sevilla · Página web · Transcripción",
    "author": "Juani de Ana Sevilla",
    "type": "Postre",
    "family": "Helados",
    "servings": "No indicadas",
    "time": "8 min + congelación",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "100 g de nueces.",
      "250 g de azúcar.",
      "5 gotas de limón.",
      "200 g de nata para montar.",
      "500 g de leche.",
      "5 yemas.",
      "1 cucharadita de maicena.",
      "1 vaina de vainilla.",
      "Ralladura de limón.",
      "Canela.",
      "Sal.",
      "Miel o azúcar invertido."
    ],
    "steps": [
      "Pica las nueces 5 s · velocidad 4.",
      "Caramelízalas con 100 g de azúcar y limón.",
      "Monta la nata y reserva.",
      "Mezcla leche, yemas, maicena y 150 g de azúcar 10 s · velocidad 5.",
      "Añade vainilla, ralladura, canela y sal; programa 8 min · 90 °C · velocidad 2.",
      "Añade miel y mezcla 1 min sin temperatura.",
      "Enfría, mezcla con la nata y añade las nueces.",
      "Congela y remueve cada 50 min."
    ],
    "presentation": "Sirve con la consistencia deseada.",
    "tips": "La crema debe enfriarse completamente antes de unirla con la nata.",
    "notes": "",
    "tags": [
      "Thermomix",
      "Helado",
      "Vainilla",
      "Nueces"
    ],
    "emoji": "🍨"
  },
  {
    "id": "rtm-0006",
    "record_type": "technique",
    "title": "Marca de calamar para arroces y fideuás",
    "origin": "Jordi Cruz · Instagram · Transcripción",
    "author": "Jordi Cruz",
    "type": "Técnica culinaria",
    "family": "Técnicas y bases",
    "servings": "No indicado",
    "time": "45 min aprox.",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "2-3 cebollas.",
      "3-4 dientes de ajo.",
      "1 kg de pulpa de tomate.",
      "Calamar fresco.",
      "Aceite de oliva.",
      "Pimentón.",
      "Azafrán, pimienta y comino.",
      "Sal.",
      "1 cucharada de tomate doble concentrado."
    ],
    "steps": [
      "Limpia el calamar y reserva recortes.",
      "Saltea el calamar picado y reserva.",
      "Pocha lentamente la cebolla.",
      "Añade el ajo.",
      "Añade pimentón y especias.",
      "Reincorpora el calamar.",
      "Añade tomate, sal y concentrado.",
      "Cocina a fuego suave unos 45 min."
    ],
    "presentation": "Úsala como base de arroces y fideuás.",
    "tips": "Puede refrigerarse o congelarse. Usa aprox. 250 g por 250 g de arroz.",
    "notes": "",
    "tags": [
      "TecnicaCulinaria",
      "MarcaDeCalamar",
      "Arroces",
      "Fideua"
    ],
    "emoji": "🦑"
  },
  {
    "id": "rtm-0007",
    "record_type": "recipe",
    "title": "Leche de almendras (Thermomix)",
    "origin": "Elaboración propia · Versión Thermomix",
    "author": "",
    "type": "Bebida",
    "family": "Técnicas y bases",
    "servings": "Aprox. 1 litro",
    "time": "10 min + 8-12 h de remojo",
    "difficulty": "Muy fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "200 g de almendras crudas peladas.",
      "1 l de agua.",
      "1 pizca de sal, opcional.",
      "1-2 dátiles o 20 g de miel, opcional.",
      "Vainilla o canela, opcional."
    ],
    "steps": [
      "Remoja las almendras 8-12 h.",
      "Escúrrelas y enjuágalas.",
      "Pon todos los ingredientes en el vaso.",
      "Tritura 2 min · velocidad 10.",
      "Cuela.",
      "Guarda en frío."
    ],
    "presentation": "Sirve fría.",
    "tips": "Se conserva 3-4 días. Agita antes de consumir.",
    "notes": "",
    "tags": [
      "Thermomix",
      "BebidaVegetal",
      "SinLactosa"
    ],
    "emoji": "🥛"
  },
  {
    "id": "rtm-0008",
    "record_type": "technique",
    "title": "Adobo tradicional para costillas y cinta de lomo",
    "origin": "Elaboración propia · Versión revisada",
    "author": "",
    "type": "Adobo · Marinada",
    "family": "Técnicas y bases",
    "servings": "Para 2 kg de carne",
    "time": "Sin cocción · 12-48 h de reposo",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "2 kg de costillas o cinta de lomo.",
      "100 ml de aceite de oliva.",
      "100 ml de vino blanco.",
      "8 dientes de ajo.",
      "30 g de pimentón dulce.",
      "Pimentón picante, opcional.",
      "Orégano.",
      "Tomillo.",
      "Comino, opcional.",
      "Laurel.",
      "20 g de sal.",
      "Pimienta negra."
    ],
    "steps": [
      "Machaca ajo y sal.",
      "Añade especias.",
      "Incorpora aceite y vino.",
      "Reparte sobre la carne.",
      "Añade laurel.",
      "Refrigera 12-48 h.",
      "Da la vuelta durante el reposo.",
      "Saca 30 min antes de cocinar."
    ],
    "presentation": "Cocina al horno, parrilla, barbacoa o sartén.",
    "tips": "No superes 48 h de marinado.",
    "notes": "",
    "tags": [
      "TecnicaCulinaria",
      "Adobo",
      "Cerdo",
      "SinVinagre"
    ],
    "emoji": "🥩"
  },
  {
    "id": "rtm-0009",
    "record_type": "recipe",
    "title": "Solomillo de cerdo con salsa de brandy y soja",
    "origin": "Red social · Transcripción",
    "author": "",
    "type": "Plato principal",
    "family": "Carne",
    "servings": "No indicadas",
    "time": "20 min de marinado + cocción",
    "difficulty": "Fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1 solomillo de cerdo.",
      "Aceite de oliva virgen extra.",
      "Sal.",
      "Pimienta negra.",
      "Ajo en polvo.",
      "1 chupito de aceite de oliva.",
      "1 chupito de brandy.",
      "3 cucharadas de salsa de soja."
    ],
    "steps": [
      "Corta el solomillo en medallones.",
      "Mézclalo con los ingredientes de la salsa.",
      "Marina 20 min.",
      "Dora los medallones.",
      "Añade la salsa.",
      "Flambea y reduce."
    ],
    "presentation": "Sirve recién hecho con la salsa.",
    "tips": "Flambea lejos de la campana extractora.",
    "notes": "",
    "tags": [
      "Carne",
      "Solomillo",
      "Brandy",
      "SalsaDeSoja"
    ],
    "emoji": "🥩"
  },
  {
    "id": "rtm-0010",
    "record_type": "recipe",
    "title": "Crema fría de espárragos blancos y anchoas",
    "origin": "Marta Martínez (@martamchef6, Instagram) · Transcripción",
    "author": "Marta Martínez",
    "type": "Entrante",
    "family": "Sopas y cremas",
    "servings": "2 personas",
    "time": "No indicado",
    "difficulty": "Muy fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1 lata de espárragos blancos.",
      "1 huevo duro.",
      "4 anchoas.",
      "1/2 diente de ajo.",
      "1 yogur natural."
    ],
    "steps": [
      "Introduce todos los ingredientes en la batidora.",
      "Tritura hasta obtener una crema homogénea."
    ],
    "presentation": "Sirve fría, con menta o albahaca si se desea.",
    "tips": "La fuente no indica tiempo de refrigeración.",
    "notes": "",
    "tags": [
      "CremaFria",
      "Esparragos",
      "Anchoas",
      "Verano"
    ],
    "emoji": "🥣"
  },
  {
    "id": "rtm-0011",
    "record_type": "recipe",
    "title": "Crema fría de piquillos y garbanzos",
    "origin": "Redes sociales · Transcripción de imagen",
    "author": "",
    "type": "Entrante",
    "family": "Sopas y cremas",
    "servings": "2 personas",
    "time": "5 min",
    "difficulty": "Muy fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "300 g de pimientos del piquillo.",
      "300 g de garbanzos cocidos.",
      "1 yogur natural.",
      "1 cucharada de aceite de oliva.",
      "Sal.",
      "Pimienta.",
      "200 ml de agua fría.",
      "Huevo cocido, tomate y cebolla, opcionales."
    ],
    "steps": [
      "Pon todos los ingredientes en la batidora.",
      "Salpimienta.",
      "Tritura hasta obtener una crema fina.",
      "Refrigera."
    ],
    "presentation": "Sirve fría con huevo cocido o tomate y cebolla.",
    "tips": "La fuente no especifica conservación.",
    "notes": "",
    "tags": [
      "CremaFria",
      "Piquillos",
      "Garbanzos",
      "Rapida",
      "SinCoccion"
    ],
    "emoji": "🥣"
  },
  {
    "id": "rtm-0012",
    "record_type": "recipe",
    "title": "Crema fría de alcachofas (Thermomix)",
    "origin": "Página web / captura de pantalla · Transcripción normalizada",
    "author": "",
    "type": "Entrante",
    "family": "Sopas y cremas",
    "servings": "4 aprox.",
    "time": "Sin cocción + refrigeración",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "2 botes de corazones de alcachofa con su líquido.",
      "3 huevos duros.",
      "150 g de cebolla tierna.",
      "1 diente de ajo.",
      "50 g de aceite de oliva.",
      "5 g de vinagre.",
      "Sal.",
      "4 lonchas de jamón serrano.",
      "Pimienta negra."
    ],
    "steps": [
      "Pon en el vaso todo excepto jamón y pimienta.",
      "Tritura 1 min 30 s · velocidad 10.",
      "Refrigera.",
      "Haz el jamón crujiente en microondas en tandas de 30 s.",
      "Desmenuza el jamón."
    ],
    "presentation": "Sirve fría con jamón crujiente, aceite y pimienta.",
    "tips": "Vigila el jamón en el microondas.",
    "notes": "",
    "tags": [
      "Thermomix",
      "Alcachofas",
      "CremaFria",
      "Verano"
    ],
    "emoji": "🥣"
  },
  {
    "id": "rtm-0013",
    "record_type": "recipe",
    "title": "Croquetas de merluza y gambas",
    "origin": "Directo al Paladar · María Pimientos · Transcripción",
    "author": "María Pimientos",
    "type": "Aperitivo",
    "family": "Pescado",
    "servings": "6 personas",
    "time": "2 h 40 min",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "150 g de merluza.",
      "150 g de gambas.",
      "150 g de aceite de oliva.",
      "200 g de harina.",
      "1 l de fumet.",
      "Sal y pimienta.",
      "Harina, huevo y pan rallado para rebozar.",
      "Aceite para freír."
    ],
    "steps": [
      "Pela las gambas.",
      "Prepara fumet si no dispones de él.",
      "Haz un roux con harina y aceite.",
      "Añade el caldo poco a poco.",
      "Incorpora merluza y gambas.",
      "Refrigera 2 h.",
      "Forma y reboza.",
      "Fríe hasta dorar."
    ],
    "presentation": "Sirve recién hechas.",
    "tips": "La masa debe reposar 2 h.",
    "notes": "",
    "tags": [
      "Croquetas",
      "Merluza",
      "Gambas",
      "Aperitivo"
    ],
    "emoji": "🐟"
  },
  {
    "id": "rtm-0014",
    "record_type": "recipe",
    "title": "Petit Suisse de fresas en vasitos",
    "origin": "El Forner de Alella · Página web · Transcripción",
    "author": "Josep Maria Mañé y Carme Julià",
    "type": "Postre",
    "family": "Postres",
    "servings": "6 vasitos",
    "time": "No indicado + refrigeración",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "500 g de fresas.",
      "250 g de queso crema.",
      "100 g de nata para montar.",
      "150 g de azúcar.",
      "5 g de cuajada en polvo."
    ],
    "steps": [
      "Lava y corta las fresas.",
      "Tritura y cuela.",
      "Pon en una cazuela.",
      "Añade nata, azúcar y queso crema.",
      "Incorpora la cuajada.",
      "Remueve hasta que empiece a hervir.",
      "Deja enfriar.",
      "Reparte en vasitos y refrigera."
    ],
    "presentation": "Sirve frío con media fresa y menta.",
    "tips": "Remueve continuamente durante la cocción.",
    "notes": "",
    "tags": [
      "PetitSuisse",
      "Fresas",
      "Postre",
      "Vasitos"
    ],
    "emoji": "🍓"
  },
  {
    "id": "rtm-0015",
    "record_type": "recipe",
    "title": "Zurracapote",
    "origin": "María Jesús Gil de Antuñano · Revista · Transcripción",
    "author": "María Jesús Gil de Antuñano",
    "type": "Postre",
    "family": "Postres",
    "servings": "4 personas",
    "time": "1 h aprox. + 2 h de remojo",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "175 g de ciruelas pasas.",
      "175 g de orejones.",
      "150 g de azúcar moreno.",
      "4 vasos de vino tinto.",
      "La misma cantidad de agua.",
      "1 palo de canela.",
      "Corteza de limón.",
      "Nata líquida."
    ],
    "steps": [
      "Remoja ciruelas y orejones 2 h.",
      "Pon vino y agua en un cazo.",
      "Añade canela, azúcar y limón.",
      "Lleva a ebullición y espuma.",
      "Añade la fruta escurrida.",
      "Cuece 25-30 min."
    ],
    "presentation": "Sirve con nata líquida.",
    "tips": "Controla el punto del almíbar.",
    "notes": "",
    "tags": [
      "Postre",
      "FrutaSeca",
      "VinoTinto"
    ],
    "emoji": "🍷"
  },
  {
    "id": "rtm-0016",
    "record_type": "recipe",
    "title": "Mousse de tres quesos",
    "origin": "María Jesús Gil de Antuñano · Revista · Transcripción",
    "author": "María Jesús Gil de Antuñano",
    "type": "Postre",
    "family": "Postres",
    "servings": "4 personas",
    "time": "1 h aprox.",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "1/4 l de nata líquida.",
      "1/4 l de leche.",
      "50 g de queso Idiazábal.",
      "50 g de queso Caprice des Dieux.",
      "2 tarrinas de queso San Millán.",
      "2 huevos.",
      "200 g de azúcar."
    ],
    "steps": [
      "Hierve leche y quesos hasta fundirlos.",
      "Tritura y enfría.",
      "Monta la nata.",
      "Bate queso San Millán, huevos y azúcar.",
      "Une las mezclas.",
      "Incorpora la nata.",
      "Reparte en copas.",
      "Refrigera."
    ],
    "presentation": "Acompaña con salsa de frutos rojos y ralladura de cítricos.",
    "tips": "La nata debe estar muy fría.",
    "notes": "La cantidad de azúcar de la fuente parece elevada; pendiente de confirmar.",
    "tags": [
      "Mousse",
      "Queso",
      "Postre"
    ],
    "emoji": "🧀"
  },
  {
    "id": "rtm-0017",
    "record_type": "recipe",
    "title": "Cocochas rebozadas",
    "origin": "María Jesús Gil de Antuñano · Revista · Transcripción",
    "author": "María Jesús Gil de Antuñano",
    "type": "Segundo plato",
    "family": "Pescado",
    "servings": "4 personas",
    "time": "30 min aprox.",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "500 g de cocochas de merluza o bacalao.",
      "2 huevos.",
      "Harina.",
      "Aceite.",
      "Sal.",
      "Pimienta.",
      "Zumo de limón.",
      "1 lata de pimientos del piquillo.",
      "1 diente de ajo.",
      "2 cucharadas de aceite.",
      "2 cucharadas de nata."
    ],
    "steps": [
      "Limpia y salpimienta las cocochas.",
      "Rocía con limón.",
      "Pasa por harina y huevo.",
      "Fríe y escurre.",
      "Dora el ajo.",
      "Rehoga los pimientos.",
      "Añade el líquido y liga.",
      "Tritura, rectifica de sal y añade nata."
    ],
    "presentation": "Sirve con la salsa de piquillos.",
    "tips": "Fríe con el aceite bien caliente.",
    "notes": "",
    "tags": [
      "Cocochas",
      "Pescado",
      "Rebozado"
    ],
    "emoji": "🐟"
  },
  {
    "id": "rtm-0018",
    "record_type": "recipe",
    "title": "Crema de cebolla al brandy",
    "origin": "María Jesús Gil de Antuñano · Revista · Transcripción",
    "author": "María Jesús Gil de Antuñano",
    "type": "Primer plato",
    "family": "Sopas y cremas",
    "servings": "4 personas",
    "time": "1 h aprox.",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "3 cebollas.",
      "1 l de caldo de ave.",
      "2 quesitos.",
      "1 yema.",
      "6 cucharadas de aceite.",
      "1 copa de brandy.",
      "Harina.",
      "Aceite para freír.",
      "Sal.",
      "Pimienta."
    ],
    "steps": [
      "Pica dos cebollas.",
      "Estófalas 30 min.",
      "Añade brandy y flambea.",
      "Añade caldo y cuece 10 min.",
      "Tritura con quesitos.",
      "Añade la yema al final.",
      "Corta la tercera cebolla en aros.",
      "Remoja, enharina y fríe."
    ],
    "presentation": "Sirve con los aros de cebolla fritos.",
    "tips": "Flambea con precaución y añade la yema sin hervor fuerte.",
    "notes": "",
    "tags": [
      "Cebolla",
      "Brandy",
      "SopasYCremas"
    ],
    "emoji": "🧅"
  },
  {
    "id": "rtm-0019",
    "record_type": "technique",
    "title": "Aceites aromatizados (Thermomix)",
    "origin": "Cuida tu salud con Thermomix, Vorwerk, pág. 30 · Transcripción",
    "author": "",
    "type": "Condimento",
    "family": "Técnicas y bases",
    "servings": "150-250 g aprox.",
    "time": "5 min / 30 s",
    "difficulty": "Muy fácil",
    "status": "Pendiente de hacer",
    "ingredients": [
      "250 g de aceite de oliva y 2 ramitas de albahaca seca, para larga duración.",
      "1 cubilete de perejil, 1 ramita de cebollino y 150 g de aceite de oliva, para uso inmediato."
    ],
    "steps": [
      "Para larga duración, programa aceite y albahaca 5 min · 100 °C · velocidad 1.",
      "Deja infusionar y envasa.",
      "Para uso inmediato, pica perejil y cebollino 10 s · velocidad 7.",
      "Añade aceite y tritura 20 s · velocidad progresiva 5-10.",
      "Cuela."
    ],
    "presentation": "Úsalos para ensaladas, verduras, pastas, arroces, carnes y pescados.",
    "tips": "El de larga duración se conserva meses; el inmediato, aprox. una semana en frío.",
    "notes": "",
    "tags": [
      "TecnicaCulinaria",
      "Aceites",
      "Thermomix",
      "AOVE"
    ],
    "emoji": "🫒"
  },
  {
    "id": "rtm-0020",
    "record_type": "recipe",
    "title": "Pa de fetge",
    "origin": "Cuines - TV3 · Página web · Transcripción",
    "author": "",
    "type": "Entrante",
    "family": "Carne y charcutería",
    "servings": "No indicadas",
    "time": "1 h 15 min + 3 h de enfriado + 2 h de remojo",
    "difficulty": "No indicada",
    "status": "Pendiente de hacer",
    "ingredients": [
      "300 g de hígado de cerdo.",
      "240 g de carne magra de cerdo.",
      "360 g de papada.",
      "100 g de cebolla.",
      "1/2 diente de ajo.",
      "2 cucharadas de mantequilla.",
      "2 huevos.",
      "18 g de sal.",
      "3 g de salitre.",
      "3 g de azúcar de caña.",
      "3 granos de pimienta negra.",
      "1 vasito de vino blanco seco.",
      "Aceite para la terrina.",
      "Pan tostado.",
      "Nueces.",
      "2 rábanos."
    ],
    "steps": [
      "Remoja el hígado 2 h.",
      "Mantén hígado, carne y papada con salitre.",
      "Pocha la cebolla con mantequilla y enfría.",
      "Mezcla carnes, sal y pimienta.",
      "Machaca el ajo y mézclalo con los huevos.",
      "Amasa todo.",
      "Añade pimienta y vino.",
      "Incorpora cebolla.",
      "Vierte en terrina aceitada.",
      "Pinta con clara.",
      "Hornea a 180 °C durante 1 h 15 min con un recipiente de agua.",
      "Enfría 3 h."
    ],
    "presentation": "Sirve con pan tostado, nueces y rábanos.",
    "tips": "Usa únicamente salitre alimentario y respeta la cantidad indicada.",
    "notes": "La fuente deja dudas sobre el uso exacto del salitre.",
    "tags": [
      "PaDeFetge",
      "Carne",
      "Charcuteria",
      "Horno",
      "CocinaCatalana"
    ],
    "emoji": "🍖"
  }
];

(function () {
  const migrationKey = "rtm_migration_sprint_2_2_20";
  const storageKey = "rtm_v1_records";
  try {
    if (!localStorage.getItem(migrationKey)) {
      localStorage.setItem(storageKey, JSON.stringify(window.RECIPES));
      localStorage.setItem(migrationKey, "done");
    }
  } catch (error) {
    console.warn("No se pudo actualizar el almacenamiento local:", error);
  }
})();
